
const recommendFilms = [
    {
        id : 1,
       arr: 'recommendFilms',
        img: './assets/image/phimLeCapNhat/SonghyeO.jpg',
        video : './assets/video/nowWeArebrk.mp4',
        name : 'Bây giờ chúng ta đang chia tay',
        year : 2021,
        episodes : 8,
        time : '8 tập',
        status : 'Đang phát',
        country : 'Phim Hàn Quốc',
        category : 'Phim tình cảm',
        type : 'Phim truyền hình',       
        directors : ['Lee Gil-bok'],
        actors : ['Song Hye-kyo', 'Jang Ki Yong', 'Choi Hee-seo'],
        content : 'Bộ phim là câu chuyện về tình yêu và việc chia tay. Phim lấy bổi cảnh hiện thực trong ngành thời trang. Ha Yeong-eun (Song Hye-kyo) là một trưởng nhóm thiết kế xinh đẹp, sành điệu, thuộc bộ phận thiết kế của công ty thời trang có tên The One. Yoon Jae-gook (Jang Ki-yong) là một nhiếp ảnh gia tự do giàu có.',
        tag : 'Now we are breaking up'
    },
    {
        id : 2,
        arr: 'recommendFilms',
        img: './assets/image/phimLeCapNhat/thatYearWe.jpg',
        video : './assets/video/ourSummer.mp4',
        name : 'That Year We',
        year : 2021,
        episodes : 6,
        time : '18 tập',
        status : 'Đang phát',
        country : 'Phim Hàn Quốc',
        category : 'Phim yimg cảm',
        type : 'Phim truyền hình',       
        directors : ['Oh Choong-Hwan'],
        actors : ['Kim Da-mi', 'Lee Sung-kyung'],
        content : 'Cô thiếu nữ ương ngạnh và từng phạm tội gặp 1 giáo viên tận tâm, rồi được truyền cảm hứng để thay đổi và trở thành bác sĩ thần kinh am hiểu cuộc sống đường phố.',
        tag : 'That Year We'
    },
    {
        id : 3,
        arr: 'recommendFilms',
        video : './assets/video/Arcane.mp4',
        img: './assets/image/decu/taySungBiAn.jpg',
        name : 'Tay súng bí ẩn',
        year : 2021,
        episodes : 0,
        time : '90 phút',
        status : 'Hoàn tất',
        country : 'Phim Mỹ',
        category : 'Phim hành động',
        type : 'Phim rạp',       
        directors : ['Potsy Ponciroli'],
        actors : ['Tim Blake Nelson', 'Scott Haze'],
        content : 'Phim xoay quanh nhân vật Henry, một người đàn ông dũng cảm và muốn xây dựng một khu đất của riêng mình cùng với con trai. Đây là một bộ phim hành động viễn tây khá xuất sắc, nhận được nhiều lời khen của khán giả và các nhà chuyên môn. Câu chuyện bắt đầu từ hai cha con bắt một người đàn ông bí ẩn bị thương với một túi tiền mặt. Khi một đội quân tự xưng là luật pháp đến đòi tiền, người nông dân phải quyết định tin tưởng ai. Bảo vệ trang trại của mình, Henry bắt buộc phải cầm súng khiến mọi người ngạc nhiên khi gọi danh tính thực sự của anh.',
        tag : 'old henry'
    },
    {
        id : 4,
        arr: 'recommendFilms',
        video : './assets/video/CrashLandingonYou.mp4',
        img: './assets/image/phimLeCapNhat/haCanhNoiAnh.jpg',
        name : 'Hạ cánh nơi anh',
        year : 2020,
        episodes : 20,
        time : '20 tập',
        status : 'Hoàn tất',
        country : 'Phim Hàn Quốc',
        category : 'Phim Tình cảm',
        type : 'Phim truyền hình',       
        directors : ['Ri Jung Hyuk'],
        actors : ['Huyn Byn', 'Son Ye-jin', 'Kim Jung-hyun', 'Seo Ji-hye'],
        content : 'Nội dung bộ phim xoay quanh chuyện tình cảm giữa một người phụ nữ xinh đẹp, giàu có và sành điệu người Hàn Quốc Yoon Seri (Son Ye Jin thủ vai) với Ri Jung Hyuk (Hyun Bin thủ vai) - một sĩ quan đại úy của quân đội Triều Tiên. Trong một lần đi chơi dù lượn, vì một trận lốc xoáy mà Seri sau đó đã vô tình lạc qua biên giới Triều Tiên và gặp "tình yêu định mệnh" với quân nhân Ri Jung Hyuk. Mối tình kẻ Nam người Bắc của Ri Jung Hyeok với ái nữ nhà tài phiệt Yoon Se Ri ngay sau đó đã chớm nảy nở.',
        tag : ' Crash Landing of Love'
    },
    {
        id : 5,
        arr: 'recommendFilms',
        img: './assets/image/decu/chachacha.jfif',
        video : './assets/video/k2.mp4',    
        name : 'Điệu Cha Cha Cha Làng Biển',
        year : 2021,
        episodes : 28,
        time : '28 tập',
        status : 'Hoàn tất',
        country : 'Phim Hàn Quốc',
        category : 'Phim Tình cảm',
        type : 'Phim truyền hình',       
        directors : ['Kwang Jung-hwan'],
        actors : ['Ji Chang-wook', 'Im Yoona ', 'Song Yoon-ah ', 'Jo Sung-ha'],
        content : 'The K2 xoay quanh Kim Je-ha (Ji Chang-wook thủ vai), một người lính yêu nước nhưng bị tổ quốc và đồng nghiệp phản bội, anh được thuê làm vệ sĩ cho Choi Yoo-jin (Song Yun-ah thủ vai), phu nhân của một ứng cử viên Tổng thống (Jo Sung-ha thủ vai), là ái nữ của một gia đình tài phiệt, luôn giấu những tham vọng của mình sau vẻ bề ngoài vô cùng ân cần, thân thiện; và Go Ahn-na (Im Yoona thủ vai), con gái riêng của vị ứng cử viên Tổng thống đó, luôn coi tình yêu chính là một loại công cụ để trả thù.',
        tag : 'Home town Cha Cha cha'
    },
    {
        id : 6,
        arr: 'recommendFilms',
        img: './assets/image/decu/hoSut.png',
        video : './assets/video/snowDrop.mp4',
        name : 'Hố sụt',
        year : 2021,
        episodes : 0,
        time : '90 phút',
        status : 'HD-Vietsub',
        country : 'Phim Mỹ',
        category : 'Phim hành động',
        type : 'Phim truyền hình',       
        directors : ['Jo Hyun-tak'],
        actors : ['Kim Ji Soo', 'Jung Hae In '],
        content : 'Hoa tuyết rơi lấy bối cảnh Phong trào đấu tranh dân chủ năm 1987 tại Hàn Quốc nhằm phản đối chính phủ độc tài thời điểm đó và yêu cầu cuộc bầu cử công bằng. Phong trào này kết thúc bằng việc chấm dứt chế độ độc tài của nền cộng hòa thứ 5 ở Hàn Quốc và nền Cộng hòa thứ 6 được thiết lập.  Bộ phim kể về câu chuyện tình đầy lãng mạn nhưng cũng đầy bi thương của hai nhân vật Im Soo-ho (Jung Hae-in) và Eun Young-ro (Kim Ji-Soo). Im Soo-ho là một sinh viên tốt nghiệp, sau khi tham gia một cuộc biểu tình ủng hộ dân chủ, đã được nữ sinh đại học Eun Young-ro vô tình phát hiện trong tình trạng dính đầy máu. Young-ro đã giúp Soo-ho trốn khỏi lực lượng chính phủ và hết lòng chữa trị cho anh bất chấp sự giám sát nghiêm ngặt. Tình yêu của hai người dần nảy nở trong bối cảnh chính trị đầy biến động..',
        tag : 'Ji Soo'
    },
    {
        id : 7,
        arr: 'recommendFilms',
        img: './assets/image/phimLeCapNhat/mayHoaAT.jpg',
        video : './assets/video/mayHoaAnhTrang.mp4',
        name : 'Mây họa ánh trăng',
        year : 2018,
        episodes : 27,
        time : '27 tập',
        status : 'Hoàn tất',
        country : 'Phim Hàn Quốc',
        category : 'Phim Tình cảm',
        type : 'Phim truyền hình',       
        directors : ['Kim Sung-yoon', 'Baek Sang-hoon'],
        actors : ['Park Bo-gum', 'Kim Yoo Jung', 'Jung Jin-young ', 'Kwak Dong-yeon'],
        content : 'Bộ phim xoay quanh sự thay đổi và trưởng thành của Vương Thế tử Lee Yeong và tình cảm của anh với cô gái tên là Hong Ra-on, một người nữ cải trang thành nam hoạn quan. Vì mưu sinh, cô nàng Hong Ra On (Kim Yoo Jung đóng) phải giả trai để làm "quân sư tình yêu", chuyên viết thư tình thay cho những nam nhân ngờ nghệch. Ra On không ngờ vị khách hàng hào phóng nhất của mình lại cả gan dùng những bức thư ấy để hẹn hò công chúa đương triều.',
        tag : 'Moonlight Drawn by Clouds'
    },
    {
        id : 8,
        arr: 'recommendFilms',
        img: './assets/image/phimLeCapNhat/dauBiet.jpg',
        video : './assets/video/Nevertheless.mp4',
        name : 'Dẫu biết',
        year : 2021,
        episodes : 9,
        time : '9 tập',
        status : 'Hoàn tất',
        country : 'Phim Hàn Quốc',
        category : 'Phim Tình cảm',
        type : 'Phim truyền hình',       
        directors : ['Ga-Ram Kim'],
        actors : ['Song Kang', 'Han So hee', 'Chae Jong-hyeop'],
        content : 'Diễn viên: Han So Hee , Song Kang, Chae Jong Hyeop, Lee Yeol Eum, Yang Hye Ji, Kim Min Gwi Dẫu Biết (Nevertheless 2021) là bộ phim của Netflix thuộc thể loại drama chính kịch. Phim xoay quanh câu chuyện của cô nàng trước sức mê hoặc của anh bạn cùng trường nghệ thuật giỏi tán tỉnh, cô nàng hoài nghi tình yêu, dù do dự vẫn bị kéo vào mối quan hệ thể xác nhưng chỉ là bạn bè.',
        tag : 'Never the less'
    },
    {
        id : 9,
        arr: 'recommendFilms',
        img: './assets/image/phimLeCapNhat/youthMay.jpg',
        video : './assets/video/YouthofMay.mp4',
        name : 'Tuổi trẻ của tháng 5',
        year : 2021,
        episodes : 17,
        time : '18 tập',
        status : 'Hoàn tất',
        country : 'Phim Hàn Quốc',
        category : 'Phim Tình cảm',
        type : 'Phim truyền hình',       
        directors : ['Song Min-yeob'],
        actors : ['Lee Do-hyeon', 'Go Min-si', 'Keum Sae-rok'],
        content : 'Tuổi Trẻ Của Tháng Năm lấy bối cảnh vào cuộc nổi dậy Gwangju xảy ra vào tháng 5 năm 1980, một khoảng thời gian có ý nghĩa lịch sử ở đất nước Hàn Quốc. Lúc này có hai thanh niên bị cuốn vào cuộc nổi dậy này đó là Hwang Hee Tae (Lee Do Hyun thủ vai), một sinh viên y khoa có tính cách tinh quái và ranh mãnh nhưng bên trong lại rất kiên định, có chí hướng. Anh vốn là một kẻ chuyên gây rối và ghét bất cứ điều gì có thể đoán trước được chính vì vậy mà cuộc sống của anh ấy được mô tả như “Cuộc chiến chống lại thành kiến”, và để phá vỡ định kiến đối với những đứa con trai được nuôi dưỡng bởi các bà mẹ đơn thân, Hee Tae đã nỗ lực để giành được điểm cao nhất và thậm chí đậu vào Đại học Y khoa của Đại học Quốc gia Seoul.',
        tag : 'Youth of May'
    },
    {
        id : 10,
        arr: 'recommendFilms',
        img: './assets/image/phimLeCapNhat/huyenThoaiBienXanh.jpg',
        video : './assets/video/TheLegend.mp4',
        name : 'Huyền thoại biển xanh',
        year : 2018,
        episodes : 24,
        time : '24 tập',
        status : 'Hoàn tất',
        country : 'Phim Hàn Quốc',
        category : 'Phim Tình cảm',
        type : 'Phim truyền hình',       
        directors : ['Jin Hyuk'],
        actors : ['Lee Min-ho', 'Jun Ji-hyun', 'Shin Won-ho', 'Lee Hee-joon'],
        content : 'Phim Huyền Thoại Biển Xanh - The Legend Of The Blue Sea được xây dựng dựa trên câu chuyện về người cá trong tập truyện Eou Yadam của học giả thời Joseon Yoo Mong In: Một vị quan có tên Kim Dang Ryung đã thả người cá trở lại đại dương, trước khi chúng bị người đánh cá bắt được',
        tag : 'The Legend Of The Blue Sea'
    },
    {
        id : 11,
        arr: 'recommendFilms',
        img: './assets/image/phimLeCapNhat/HDMT.jpg',
        video : './assets/video/Descendants.mp4',
        name : 'Hậu duệ mặt trời',
        year : 2016,
        episodes : 16,
        time : '16 tập',
        status : 'Hoàn tất',
        country : 'Phim Hàn Quốc',
        category : 'Phim Tình cảm',
        type : 'Phim truyền hình',       
        directors : ['Baek Sang-hoon'],
        actors : ['Song Joong Ki', 'Song Hye Kyo', 'Jin Goo', 'Kim Ji Won'],
        content : 'Hậu Duệ Mặt Trời có nội dung phim xoay quanh hai nhân vật Yoo Shi Jin và Kang Mo Yeon. Yoo Shi Jin là đội trưởng lực lượng gìn giữ hòa bình của Liên Hợp Quốc. Trong khi đó, Kang Mo Yeon là thành viên của tổ chức Bác sĩ không biên giới. Thời gian đầu gặp gỡ và hợp tác, Shi Jin và Mo Yeon thường xuyên xảy ra xung đột. Tuy nhiên về sau, mối quan hệ giữa họ dần được cải thiện. Trải qua nhiều lần xông pha vào chốn hiểm nguy, cả hai đã nhận ra tình cảm dành cho nhau',
        tag : 'Descentdant of the Sun'
    },
    {
        id : 12,
        arr: 'recommendFilms',
        img: './assets/image/phimLeCapNhat/REPLY1988.jpg',
        video : './assets/video/Reply1988.mp4',
        name : 'Reply 1988',
        year : '2016',
        episodes : 21,
        time : '21 tập',
        status : 'Hoàn tất',
        country : 'Phim Hàn Quốc',
        category : 'Phim Tâm Lý - Tình Cảm, Hài Hước',
        type : 'Phim truyền hình',       
        directors : ['Shin Won-ho'],
        actors : ['Lee Hye-ri', 'Ryu Jun-yeol', 'Park Bo-gum', 'Go Kyung-pyo'],
        content : 'Bộ phim thứ ba của những nhà sản xuất đã từng rất thành công với hai phim trước đó là “Lời hồi đáp 1997” và “Lời hồi đáp 1994” đã được lên kế hoạch từ cuối năm 2013 (khi “Lời hồi đáp 1994” vừa đóng máy). Quá trình sản xuất bị đình trệ khá lâu trong năm vừa qua, nhưng giờ đây với bộ phim “Misaeng” như một tấm gương phản chiếu, tvN đang háo hức hơn bao giờ hết khi được mời Đạo diễn Shin Won-ho và biên kịch Lee Woo-jung hợp tác với họ để sản xuất bộ phim vẫn chưa được đặt tên chính thức ấy (mà rất có thể sẽ trở thành một thành công lớn tiếp theo).',
        tag : 'Lee Hye-ri yêu Ryu Jun-yeol'
    },
    {
        id : 13,
        arr: 'recommendFilms',
        img: './assets/image/phimLeCapNhat/chuyenTinhBacSi.jpg',
        video : './assets/video/Doctors.mp4',
        name : 'Chuyện tình bác sĩ',
        year : 2017,
        episodes : 30,
        time : '30 tập',
        status : 'Hoàn tất',
        country : 'Phim Hàn Quốc',
        category : 'Phim Tình cảm',
        type : 'Phim truyền hình',       
        directors : ['Oh Choong-Hwan'],
        actors : ['Park Shin-hye', 'Kim Rae-won', 'Lee Sung-kyung', 'Kim Ji-soo'],
        content : 'Cô thiếu nữ ương ngạnh và từng phạm tội gặp 1 giáo viên tận tâm, rồi được truyền cảm hứng để thay đổi và trở thành bác sĩ thần kinh am hiểu cuộc sống đường phố.',
        tag : 'Doctors Love'
    },
    {
        id : 14,
        arr: 'recommendFilms',
        img: './assets/image/decu/thayCung.jpg',
        video : './assets/video/moonLover.mp4',
        name : 'Thầy cúng/ Bà đồng',
        year : 2021,
        episodes : 0,
        time : '97 phút',
        status : 'HD-Vietsub',
        country : 'Phim Thái',
        category : 'Phim kinh dị',
        type : 'Phim rạp',       
        directors : ['Kim Kyu-tae'],
        actors : ['Lee Joon-gi', 'IU', 'Byeon Baek Hyeon', 'Nam Joo-hyuk'],
        content : 'Người tình ánh trăng - Bộ bộ kinh tâm: Lệ là một bộ phim truyền hình Hàn Quốc được chuyển thể từ cuốn tiểu thuyết Bộ Bộ Kinh Tâm của nhà văn Trung Quốc Đồng Hoa.',
        tag : 'Moon Love'
    },
    {
        id : 15,
        arr: 'recommendFilms',
        img: './assets/image/phimMoiCN/bietDoiTruyQuetMT.jfif',
        video : './assets/video/tryQuetMatuy.mp4',
        name : 'Biệt đội truy quét ma túy',
        year : 2021,
        episodes : 0,
        time : '95 phút',
        status : 'HD-VietSub',
        country : 'Phim Trung Quốc',
        category : 'Phim hành động',
        type : 'Phim rạp',       
        directors : ['XUE WEN HUA'],
        actors : ['RYANG ZHANG', 'DONG ZHENG', 'LI XIN ZHE'],
        content : 'Drug Hunting Operation Dưới sự lãnh đạo của đội trưởng Li Guangfeng, Wang Xin, một cảnh sát chống ma túy trẻ tuổi trở về sau khóa huấn luyện đặc biệt tại Nam Mỹ, đã phát động một chiến dịch chống ma túy dưới mật danh "Operation Flash" nhằm phá vỡ âm mưu của trùm ma túy quốc tế Jin Ye và tay buôn ma túy xảo quyệt Xu Dahong. Đối đầu giữa trắng và trắng, đấu tranh giữa thiện và ác, cảnh sát phòng chống ma túy tiền tuyến bắt đầu cuộc chiến chống ma túy bên bờ biển với tinh thần quả cảm, ngoan cường và dám hy sinh!',
        tag : 'drug hunting operation'
    },
    {
        id : 16,
        arr: 'recommendFilms',
        img: './assets/image/phimMoiCN/demTruocSuHo.jpg',
        video : './assets/video/SOHO.mp4',
        name : 'Đêm trước ở SUHO',
        year : 2021,
        episodes : 0,
        time : '90 phút',
        status : 'Hoàn tất',
        country : 'Phim Mỹ',
        category : 'Phim Hành Động',
        type : 'Phim rạp',       
        directors : ['Edgar Wright'],
        actors : ['Edgar Wright'],
        content : 'Đêm Trước Ở Soho - Last Night in Soho xoay quanh câu chuyện về một người phụ nữ trẻ tuổi có niềm đam mê với ngành nghề thời trang. Thế nhưng, một hôm cô bỗng nhiên quay trở về lại quá khứ vào năm 1960, tại đây cô đã gặp gỡ được vị thần tượng của mình là nữ ca sĩ Wannabe đầy quyết rũ và hào quang. Tuy nhiên, cuộc sống vào năm 1960 không hề như những gì cô nghĩ, nơi đây trang ngập đầy những điều huyền bí và nguy hiểm, và những thứ kinh hoàng mà cô gái sắp phải đối mặt.',
        tag : 'The last night in SOHO'
    },
    {
        id : 17,
        arr: 'recommendFilms',
        img: './assets/image/decu/laoGiaFinch.jfif',
        video : './assets/video/TheLegend.mp4',
        name : 'Lão Già Finch',
        year : 2021,
        episodes : 0,
        time : '95 tập',
        status : 'Hoàn tất',
        country : 'Phim Mỹ',
        category : 'Phim hài',
        type : 'Phim rạp',       
        directors : ['Jin Hyuk'],
        actors : ['Lee Min-ho', 'Jun Ji-hyun', 'Shin Won-ho', 'Lee Hee-joon'],
        content : 'Lão Già Finch - The Legend Of The Blue Sea được xây dựng dựa trên câu chuyện về người cá trong tập truyện Eou Yadam của học giả thời Joseon Yoo Mong In: Một vị quan có tên Kim Dang Ryung đã thả người cá trở lại đại dương, trước khi chúng bị người đánh cá bắt được',
        tag : 'Finch'
    },
    {
        id : 18,
        arr: 'recommendFilms',
        img: './assets/image/decu/myName.jfif',
        video : './assets/video/myName.mp4',
        name : 'Tên của tôi',
        year : 2021,
        episodes : 8,
        time : '8 tập' ,
        status : 'Hoàn tất',
        country : 'Phim Hàn Quốc',
        category : 'Hành động, Giật gân, Đen, Tội phạm',
        type : 'Phim truyền hình',       
        directors : ['Kim Jin-min'],
        actors : ['Han So-hee', 'Ahn Bo-hyun', 'Park Hee-soon'],
        content : 'My Name là một bộ phim truyền hình trực tuyến của Hàn Quốc do Kim Ji-min đảm nhiệm vai trò đạo diễn, cùng với các diễn viên Han So-hee, Park Hee-soon và Ahn Bo-hyun. Bộ phim xoay quanh một người phụ nữ tham gia vào một băng đảng tội phạm rồi sau đó trở thành một cảnh sát ngầm để tìm hiểu về cái chết của cha cô. ',
        tag : 'My name'
    },
    {
        id : 19,
        arr: 'recommendFilms',
        img: './assets/image/decu/NoDie.jfif',
        video : './assets/video/moonLover.mp4',
        name : 'Không phải lúc chết',
        year : 2021,
        episodes : 0,
        time : '90 phút',
        status : 'HD-Vietsub',
        country : 'Phim Mỹ',
        category : 'Phim hành động',
        type : 'Phim rạp',       
        directors : ['Kim Kyu-tae'],
        actors : ['Lee Joon-gi', 'IU', 'Byeon Baek Hyeon', 'Nam Joo-hyuk'],
        content : 'Người tình ánh trăng - Bộ bộ kinh tâm: Lệ là một bộ phim truyền hình Hàn Quốc được chuyển thể từ cuốn tiểu thuyết Bộ Bộ Kinh Tâm của nhà văn Trung Quốc Đồng Hoa.',
        tag : 'no die'
    },
    {
        id : 20,
        arr: 'recommendFilms',
        img: './assets/image/decu/picachu.jfif',
        video : './assets/video/F20.mp4',
        name : 'Pokemon: Bí mật rừng rậm (bản điện ảnh)',
        year : 2021,
        episodes : 0,
        time : '96 phút',
        status : 'sắp chiếu',
        country : 'Phim Mỹ',
        category : 'Phim hoạt hình',
        type : 'Phim rạp',       
        directors : ['Hong eun mi'],
        actors : ['jang jong nam', 'Kim Kang Min', 'Yoo Do-hyun'],
        content : ' kể về Ae Ran một người mẹ đơn thân và có một cậu con trai là Do Hoon hiện đang trong thời gian nhập ngũ, cô luôn tự hào về cậu con trai hiền lành và ngoan ngoãn của mình. Thế nhưng, bỗng một hôm cuộc sống của cô suy sụp sau khi phát hiện ra cậu con trai Do Hoon rời khỏi quân ngũ và mắc phải chứng bệnh tâm thần phân liệt. Vì không muốn Do Hoon sống khổ sở nên Ae Ran đã quyết định che giấu đi bệnh của cậu và sống như bình thường. Tuy nhiên, mọi chuyện thay đổi sau khi xuất hiện Kyeong Hwa, người đã biết được các bí mật mà Ae Ran đã che giấu.a.',
        tag : ' Pokemon'
    },
    {
        id : 21,
        arr: 'recommendFilms',
        img: './assets/image/decu/squidGame.jfif',
        video : './assets/image/decu/squidGame.jfif',
        name : 'Trò chơi con mực',
        year : 2021,
        episodes : 9,
        time : '9 tập',
        status : 'Hoàn tất',
        country : 'Phim Hàn Quốc',
        category : 'Kinh dị viễn tưởng',
        type : 'Phim truyền hình',       
        directors : ['Hwang Dong-hyuk'],
        actors : ['Lee Jung-jae', 'Park Hae-soo', 'Wi Ha-joon', 'Jung Ho-yeon'],
        content : 'Hàng trăm người chơi kẹt tiền chấp nhận một lời mời kỳ lạ: thi đấu trong các trò chơi trẻ con. Đón chờ họ là một giải thưởng hấp dẫn – và những rủi ro chết người.',
        tag : 'squid Game'
    },
    {
        id : 22,
        arr: 'recommendFilms',
        img: './assets/image/decu/Adas2.jfif',
        video : './assets/video/THEADDAMS.mp4',
        name : 'Gia đình Aaddams',
        year : 2021,
        episodes : 0,
        time : '90 phút',
        status : 'HD-vietsub',
        country : 'Phim Mỹ',
        category : 'Phim hoạt hình',
        type : 'Phim rạp',       
        directors : ['Charlize Theron'],
        actors : ['Chloë Grace Moretz', 'javon waltong'],
        content : 'Được dịch từ tiếng Anh-Gia đình Addams 2 là bộ phim hài đen siêu nhiên hoạt hình máy tính năm 2021 do Greg Tiernan và Conrad Vernon đạo diễn, Laura Brousseau và Kevin Pavlovic đồng đạo diễn, Dan Hernandez, Benji Samit, Ben Queen và Susanna Fogel viết kịch bản với một câu chuyện của Hernandez và Samit, và dựa trên các nhân vật do Charles ',
        tag : 'The addams family'
    },
    {
        id : 23,
        arr: 'recommendFilms',
        img: './assets/image/decu/luyenmo.jfif',
        video : './assets/video/luyenMo.mp4',
        name : 'Luyến mộ',
        year : 2021,
        episodes : 9,
        time : '28 tập',
        status : 'Đang chiếu',
        country : 'Phim Hàn Quốc',
        category : 'Phim tìm cảm',
        type : 'Phim truyền hình',       
        directors : ['Park Eun-hye'],
        actors : ['Park Eun-bin', 'Rowoon'],
        content : 'Bộ phim lấy bối cảnh vào triều đại Joseon, vào thời điểm mà các cặp song sinh bị coi là điềm gở. Thế tử tần - chính thất của Thế tử lúc bấy giờ (tức Đại vương Ye-jong sau này) vô tình sinh ra một cặp song sinh trai gái là Lee Hwi và Dam I. Để tránh đem lại điềm gở cho vương thất, bé gái Dam I bị buộc phải chết. Để cứu con gái mình, bà đã bí mật đem đứa trẻ ra khỏi cung điện. Vài năm sau, cậu con trai - thế tử Lee Hwi - bất ngờ bị ám sát; trong khi người con gái Dam I lại vô tình trở thành cung nữ trong nội cung.',
        tag : 'The king'
    },
    {
        id : 24,
        arr: 'recommendFilms',
        img: './assets/image/decu/sangNhuTr.jfif',
        video : './assets/video/F20.mp4',
        name : 'Sáng Như Trăng Trong Mây',
        year : 2021,
        episodes : 19,
        time : '34 tập',
        status : 'Đang chiếu',
        country : 'Phim Trung Quốc',
        category : 'Phim tình cảm',
        type : 'Phim truyền hình',       
        directors : ['Hong eun mi'],
        actors : ['jang jong nam', 'Kim jung joung', 'Kim Kang Min', 'Yoo Do-hyun'],
        content : 'F20 kể về Ae Ran một người mẹ đơn thân và có một cậu con trai là Do Hoon hiện đang trong thời gian nhập ngũ, cô luôn tự hào về cậu con trai hiền lành và ngoan ngoãn của mình. Thế nhưng, bỗng một hôm cuộc sống của cô suy sụp sau khi phát hiện ra cậu con trai Do Hoon rời khỏi quân ngũ và mắc phải chứng bệnh tâm thần phân liệt. Vì không muốn Do Hoon sống khổ sở nên Ae Ran đã quyết định che giấu đi bệnh của cậu và sống như bình thường. Tuy nhiên, mọi chuyện thay đổi sau khi xuất hiện Kyeong Hwa, người đã biết được các bí mật mà Ae Ran đã che giấu.a.',
        tag : 'F20'
    },
    {
        id : 25,
        arr: 'recommendFilms',
        img: './assets/image/decu/noHoa.jpg',
        video : './assets/video/F20.mp4',
        name : 'Nộ hỏa',
        year : 2021,
        episodes : 0,
        time : '97 phút',
        status : 'HD-VietSub',
        country : 'Phim Hàn Quốc',
        category : 'Phim tâm lí',
        type : 'Phim truyền hình',       
        directors : ['Hong eun mi'],
        actors : ['jang jong nam', 'Kim jung joung', 'Kim Kang Min', 'Yoo Do-hyun'],
        content : 'F20 kể về Ae Ran một người mẹ đơn thân và có một cậu con trai là Do Hoon hiện đang trong thời gian nhập ngũ, cô luôn tự hào về cậu con trai hiền lành và ngoan ngoãn của mình. Thế nhưng, bỗng một hôm cuộc sống của cô suy sụp sau khi phát hiện ra cậu con trai Do Hoon rời khỏi quân ngũ và mắc phải chứng bệnh tâm thần phân liệt. Vì không muốn Do Hoon sống khổ sở nên Ae Ran đã quyết định che giấu đi bệnh của cậu và sống như bình thường. Tuy nhiên, mọi chuyện thay đổi sau khi xuất hiện Kyeong Hwa, người đã biết được các bí mật mà Ae Ran đã che giấu.a.',
        tag : 'fury'
    },
    {
        id : 26,
        arr: 'recommendFilms',
        img: './assets/image/decu/soCanhSat.jpg',
        video : './assets/video/Descendants.mp4',
        name : 'Sở cảnh sát',
        year : 2021,
        episodes : 0,
        time : '117 phút',
        status : 'HD-VietSub',
        country : 'Phim Mỹ',
        category : 'Phim Hành động',
        type : 'Phim rạp',       
        directors : ['Baek Sang-hoon'],
        actors : ['Song Joong Ki', 'Song Hye Kyo', 'Jin Goo', 'Kim Ji Won'],
        content : 'Hậu Duệ Mặt Trời có nội dung phim xoay quanh hai nhân vật Yoo Shi Jin và Kang Mo Yeon. Yoo Shi Jin là đội trưởng lực lượng gìn giữ hòa bình của Liên Hợp Quốc. Trong khi đó, Kang Mo Yeon là thành viên của tổ chức Bác sĩ không biên giới. Thời gian đầu gặp gỡ và hợp tác, Shi Jin và Mo Yeon thường xuyên xảy ra xung đột. Tuy nhiên về sau, mối quan hệ giữa họ dần được cải thiện. Trải qua nhiều lần xông pha vào chốn hiểm nguy, cả hai đã nhận ra tình cảm dành cho nhau',
        tag : 'police station'
    },
    {
        id : 27,
        arr: 'recommendFilms',
        img: './assets/image/decu/vucSauThuHan.png',
        video : './assets/video/Reply1988.mp4',
        name : 'Vực sâu thù hận',
        year : 2021,
        episodes : 21,
        time : '21 tập',
        status : 'HD-VietSub',
        country : 'Phim Mỹ',
        category : 'Phim hành động',
        type : 'Phim rạp',       
        directors : ['Shin Won-ho'],
        actors : ['Lee Hye-ri', 'Ryu Jun-yeol', 'Park Bo-gum', 'Go Kyung-pyo'],
        content : 'Bộ phim thứ ba của những nhà sản xuất đã từng rất thành công với hai phim trước đó là “Lời hồi đáp 1997” và “Lời hồi đáp 1994” đã được lên kế hoạch từ cuối năm 2013 (khi “Lời hồi đáp 1994” vừa đóng máy). Quá trình sản xuất bị đình trệ khá lâu trong năm vừa qua, nhưng giờ đây với bộ phim “Misaeng” như một tấm gương phản chiếu, tvN đang háo hức hơn bao giờ hết khi được mời Đạo diễn Shin Won-ho và biên kịch Lee Woo-jung hợp tác với họ để sản xuất bộ phim vẫn chưa được đặt tên chính thức ấy (mà rất có thể sẽ trở thành một thành công lớn tiếp theo).',
        tag : 'Abyss of hatred'
    },
    {
        id : 28,
        arr: 'recommendFilms',
        img: './assets/image/decu/maBupBeChupky.jpg',
        video : './assets/video/Doctors.mp4',
        name : 'Ma búp bê Chucky',
        year : 2021,
        episodes : 6,
        time : '30 tập',
        status : 'Hoàn tất',
        country : 'Phim Mỹ',
        category : 'Phim kinh dị',
        type : 'Phim rạp',       
        directors : ['Oh Choong-Hwan'],
        actors : ['Park Shin-hye', 'Kim Rae-won', 'Lee Sung-kyung', 'Kim Ji-soo'],
        content : 'Cô thiếu nữ ương ngạnh và từng phạm tội gặp 1 giáo viên tận tâm, rồi được truyền cảm hứng để thay đổi và trở thành bác sĩ thần kinh am hiểu cuộc sống đường phố.',
        tag : 'Doctors Love'
    },
    {
        id : 29,
        arr: 'recommendFilms',
        img: './assets/image/decu/xacSong.jfif',
        video : './assets/video/moonLover.mp4',
        name : 'Xác sống phần 11',
        year : 2021,
        episodes : 0,
        time : '110 phút',
        status : 'HD-Vietsub',
        country : 'Phim Hàn Quốc',
        category : 'Phim Tình cảm',
        type : 'Phim truyền hình',       
        directors : ['Kim Kyu-tae'],
        actors : ['Lee Joon-gi', 'IU', 'Byeon Baek Hyeon', 'Nam Joo-hyuk'],
        content : 'Người tình ánh trăng - Bộ bộ kinh tâm: Lệ là một bộ phim truyền hình Hàn Quốc được chuyển thể từ cuốn tiểu thuyết Bộ Bộ Kinh Tâm của nhà văn Trung Quốc Đồng Hoa.',
        tag : 'zombie'
    },
    {
        id : 30,
        arr: 'recommendFilms',
        img: '/assets/image/decu/Newark.jpg',
        video : './assets/video/tryQuetMatuy.mp4',
        name : 'Thoát khỏi Mogadishu',
        year : 2021,
        episodes :0,
        time : '95 phút',
        status : 'HD-VietSub',
        country : 'Phim Trung Quốc',
        category : 'Phim hành động',
        type : 'Phim rạp',       
        directors : ['XUE WEN HUA'],
        actors : ['RYANG ZHANG', 'DONG ZHENG', 'LI XIN ZHE'],
        content : 'Drug Hunting Operation Dưới sự lãnh đạo của đội trưởng Li Guangfeng, Wang Xin, một cảnh sát chống ma túy trẻ tuổi trở về sau khóa huấn luyện đặc biệt tại Nam Mỹ, đã phát động một chiến dịch chống ma túy dưới mật danh "Operation Flash" nhằm phá vỡ âm mưu của trùm ma túy quốc tế Jin Ye và tay buôn ma túy xảo quyệt Xu Dahong. Đối đầu giữa trắng và trắng, đấu tranh giữa thiện và ác, cảnh sát phòng chống ma túy tiền tuyến bắt đầu cuộc chiến chống ma túy bên bờ biển với tinh thần quả cảm, ngoan cường và dám hy sinh!',
        tag : 'exit Mogadishu'
    },
]
export default recommendFilms
export const seriesMovieSmall = [
    {
        id : 2,
        arr: 'seriesMovieSmall',
        img: './assets/image/phimLeCapNhat/SonghyeO.jpg',
        video : './assets/video/nowWeArebrk.mp4',
        name : 'Bây giờ chúng ta đang chia tay',
        year : 2021,
        episodes : 8,
        time : '8 tập',
        status : 'Đang phát',
        country : 'Phim Hàn Quốc',
        category : 'Phim tình cảm',
        type : 'Phim truyền hình',       
        directors : ['Lee Gil-bok'],
        actors : ['Song Hye-kyo', 'Jang Ki Yong', 'Choi Hee-seo'],
        content : 'Bộ phim là câu chuyện về tình yêu và việc chia tay. Phim lấy bổi cảnh hiện thực trong ngành thời trang. Ha Yeong-eun (Song Hye-kyo) là một trưởng nhóm thiết kế xinh đẹp, sành điệu, thuộc bộ phận thiết kế của công ty thời trang có tên The One. Yoon Jae-gook (Jang Ki-yong) là một nhiếp ảnh gia tự do giàu có.',
        tag : 'Now we are breaking up'
    },
    {
        id : 3,
        arr: 'seriesMovieSmall',
        img: './assets/image/phimLeCapNhat/2014_Moon_Lovers.jpg',
        video : './assets/video/moonLover.mp4',
        name : 'Người tình ánh trăng',
        year : 2016,
        episodes : 24,
        time : '24 tập',
        status : 'Hoàn tất',
        country : 'Phim Hàn Quốc',
        category : 'Phim Tình cảm',
        type : 'Phim truyền hình',       
        directors : ['Kim Kyu-tae'],
        actors : ['Lee Joon-gi', 'IU', 'Byeon Baek Hyeon', 'Nam Joo-hyuk'],
        content : 'Người tình ánh trăng - Bộ bộ kinh tâm: Lệ là một bộ phim truyền hình Hàn Quốc được chuyển thể từ cuốn tiểu thuyết Bộ Bộ Kinh Tâm của nhà văn Trung Quốc Đồng Hoa.',
        tag : 'Moon Love'
    },
    {
        id : 4,
        arr: 'seriesMovieSmall',
        video : './assets/video/CrashLandingonYou.mp4',
        img: './assets/image/phimLeCapNhat/haCanhNoiAnh.jpg',
        name : 'Hạ cánh nơi anh',
        year : 2020,
        episodes : 20,
        time : '20 tập',
        status : 'Hoàn tất',
        country : 'Phim Hàn Quốc',
        category : 'Phim Tình cảm',
        type : 'Phim truyền hình',       
        directors : ['Ri Jung Hyuk'],
        actors : ['Huyn Byn', 'Son Ye-jin', 'Kim Jung-hyun', 'Seo Ji-hye'],
        content : 'Nội dung bộ phim xoay quanh chuyện tình cảm giữa một người phụ nữ xinh đẹp, giàu có và sành điệu người Hàn Quốc Yoon Seri (Son Ye Jin thủ vai) với Ri Jung Hyuk (Hyun Bin thủ vai) - một sĩ quan đại úy của quân đội Triều Tiên. Trong một lần đi chơi dù lượn, vì một trận lốc xoáy mà Seri sau đó đã vô tình lạc qua biên giới Triều Tiên và gặp "tình yêu định mệnh" với quân nhân Ri Jung Hyuk. Mối tình kẻ Nam người Bắc của Ri Jung Hyeok với ái nữ nhà tài phiệt Yoon Se Ri ngay sau đó đã chớm nảy nở.',
        tag : ' Crash Landing of Love'
    },
    {
        id : 5,
        arr: 'seriesMovieSmall',
        img: './assets/image/phimLeCapNhat/matdanhk2.jpg',
        video : './assets/video/k2.mp4',    
        name : 'Mật danh k2',
        year : 2018,
        episodes : 28,
        time : '28 tập',
        status : 'Hoàn tất',
        country : 'Phim Hàn Quốc',
        category : 'Phim Tình cảm',
        type : 'Phim truyền hình',       
        directors : ['Kwang Jung-hwan'],
        actors : ['Ji Chang-wook', 'Im Yoona ', 'Song Yoon-ah ', 'Jo Sung-ha'],
        content : 'The K2 xoay quanh Kim Je-ha (Ji Chang-wook thủ vai), một người lính yêu nước nhưng bị tổ quốc và đồng nghiệp phản bội, anh được thuê làm vệ sĩ cho Choi Yoo-jin (Song Yun-ah thủ vai), phu nhân của một ứng cử viên Tổng thống (Jo Sung-ha thủ vai), là ái nữ của một gia đình tài phiệt, luôn giấu những tham vọng của mình sau vẻ bề ngoài vô cùng ân cần, thân thiện; và Go Ahn-na (Im Yoona thủ vai), con gái riêng của vị ứng cử viên Tổng thống đó, luôn coi tình yêu chính là một loại công cụ để trả thù.',
        tag : 'THE K2'
    },
    {
        id : 6,
        arr: 'seriesMovieSmall',
        img: './assets/image/phimLeCapNhat/mayHoaAT.jpg',
        video : './assets/video/mayHoaAnhTrang.mp4',
        name : 'Mây họa ánh trăng',
        year : 2018,
        episodes : 27,
        time : '27 tập',
        status : 'Hoàn tất',
        country : 'Phim Hàn Quốc',
        category : 'Phim Tình cảm',
        type : 'Phim truyền hình',       
        directors : ['Kim Sung-yoon', 'Baek Sang-hoon'],
        actors : ['Park Bo-gum', 'Kim Yoo Jung', 'Jung Jin-young ', 'Kwak Dong-yeon'],
        content : 'Bộ phim xoay quanh sự thay đổi và trưởng thành của Vương Thế tử Lee Yeong và tình cảm của anh với cô gái tên là Hong Ra-on, một người nữ cải trang thành nam hoạn quan. Vì mưu sinh, cô nàng Hong Ra On (Kim Yoo Jung đóng) phải giả trai để làm "quân sư tình yêu", chuyên viết thư tình thay cho những nam nhân ngờ nghệch. Ra On không ngờ vị khách hàng hào phóng nhất của mình lại cả gan dùng những bức thư ấy để hẹn hò công chúa đương triều.',
        tag : 'Moonlight Drawn by Clouds'
    },
    {
        id : 7,
        arr: 'seriesMovieSmall',
        img: './assets/image/phimLeCapNhat/dauBiet.jpg',
        video : './assets/video/Nevertheless.mp4',
        name : 'Dẫu biết',
        year : 2021,
        episodes : 9,
        time : '9 tập',
        status : 'Hoàn tất',
        country : 'Phim Hàn Quốc',
        category : 'Phim Tình cảm',
        type : 'Phim truyền hình',       
        directors : ['Ga-Ram Kim'],
        actors : ['Song Kang', 'Han So hee', 'Chae Jong-hyeop'],
        content : 'Diễn viên: Han So Hee , Song Kang, Chae Jong Hyeop, Lee Yeol Eum, Yang Hye Ji, Kim Min Gwi Dẫu Biết (Nevertheless 2021) là bộ phim của Netflix thuộc thể loại drama chính kịch. Phim xoay quanh câu chuyện của cô nàng trước sức mê hoặc của anh bạn cùng trường nghệ thuật giỏi tán tỉnh, cô nàng hoài nghi tình yêu, dù do dự vẫn bị kéo vào mối quan hệ thể xác nhưng chỉ là bạn bè.',
        tag : 'Never the less'
    },

]
export const seriesMovieBot = [
    {
        id : 8,
        arr: 'seriesMovieBot',
        img: './assets/image/phimLeCapNhat/youthMay.jpg',
        video : './assets/video/YouthofMay.mp4',
        name : 'Tuổi trẻ của tháng 5',
        year : 2021,
        episodes : 17,
        time : '18 tập',
        status : 'Hoàn tất',
        country : 'Phim Hàn Quốc',
        category : 'Phim Tình cảm',
        type : 'Phim truyền hình',       
        directors : ['Song Min-yeob'],
        actors : ['Lee Do-hyeon', 'Go Min-si', 'Keum Sae-rok'],
        content : 'Tuổi Trẻ Của Tháng Năm lấy bối cảnh vào cuộc nổi dậy Gwangju xảy ra vào tháng 5 năm 1980, một khoảng thời gian có ý nghĩa lịch sử ở đất nước Hàn Quốc. Lúc này có hai thanh niên bị cuốn vào cuộc nổi dậy này đó là Hwang Hee Tae (Lee Do Hyun thủ vai), một sinh viên y khoa có tính cách tinh quái và ranh mãnh nhưng bên trong lại rất kiên định, có chí hướng. Anh vốn là một kẻ chuyên gây rối và ghét bất cứ điều gì có thể đoán trước được chính vì vậy mà cuộc sống của anh ấy được mô tả như “Cuộc chiến chống lại thành kiến”, và để phá vỡ định kiến đối với những đứa con trai được nuôi dưỡng bởi các bà mẹ đơn thân, Hee Tae đã nỗ lực để giành được điểm cao nhất và thậm chí đậu vào Đại học Y khoa của Đại học Quốc gia Seoul.',
        tag : 'Youth of May'
    },
    {
        id : 9,
        arr: 'seriesMovieBot',
        img: './assets/image/phimLeCapNhat/huyenThoaiBienXanh.jpg',
        video : './assets/video/TheLegend.mp4',
        name : 'Huyền thoại biển xanh',
        year : 2018,
        episodes : 24,
        time : '24 tập',
        status : 'Hoàn tất',
        country : 'Phim Hàn Quốc',
        category : 'Phim Tình cảm',
        type : 'Phim truyền hình',       
        directors : ['Jin Hyuk'],
        actors : ['Lee Min-ho', 'Jun Ji-hyun', 'Shin Won-ho', 'Lee Hee-joon'],
        content : 'Phim Huyền Thoại Biển Xanh - The Legend Of The Blue Sea được xây dựng dựa trên câu chuyện về người cá trong tập truyện Eou Yadam của học giả thời Joseon Yoo Mong In: Một vị quan có tên Kim Dang Ryung đã thả người cá trở lại đại dương, trước khi chúng bị người đánh cá bắt được',
        tag : 'The Legend Of The Blue Sea'
    },
    {
        id : 11,
        arr: 'seriesMovieBot',
        img: './assets/image/phimLeCapNhat/HDMT.jpg',
        video : './assets/video/Descendants.mp4',
        name : 'Hậu duệ mặt trời',
        year : 2016,
        episodes : 16,
        time : '16 tập',
        status : 'Hoàn tất',
        country : 'Phim Hàn Quốc',
        category : 'Phim Tình cảm',
        type : 'Phim truyền hình',       
        directors : ['Baek Sang-hoon'],
        actors : ['Song Joong Ki', 'Song Hye Kyo', 'Jin Goo', 'Kim Ji Won'],
        content : 'Hậu Duệ Mặt Trời có nội dung phim xoay quanh hai nhân vật Yoo Shi Jin và Kang Mo Yeon. Yoo Shi Jin là đội trưởng lực lượng gìn giữ hòa bình của Liên Hợp Quốc. Trong khi đó, Kang Mo Yeon là thành viên của tổ chức Bác sĩ không biên giới. Thời gian đầu gặp gỡ và hợp tác, Shi Jin và Mo Yeon thường xuyên xảy ra xung đột. Tuy nhiên về sau, mối quan hệ giữa họ dần được cải thiện. Trải qua nhiều lần xông pha vào chốn hiểm nguy, cả hai đã nhận ra tình cảm dành cho nhau',
        tag : 'Descentdant of the Sun'
    },
    {
        id : 12,
        arr: 'seriesMovieBot',
        img: './assets/image/phimLeCapNhat/REPLY1988.jpg',
        video : './assets/video/Reply1988.mp4',
        name : 'Reply 1988',
        year : '2016',
        episodes : 21,
        time : '21 tập',
        status : 'Hoàn tất',
        country : 'Phim Hàn Quốc',
        category : 'Phim Tâm Lý - Tình Cảm, Hài Hước',
        type : 'Phim truyền hình',       
        directors : ['Shin Won-ho'],
        actors : ['Lee Hye-ri', 'Ryu Jun-yeol', 'Park Bo-gum', 'Go Kyung-pyo'],
        content : 'Bộ phim thứ ba của những nhà sản xuất đã từng rất thành công với hai phim trước đó là “Lời hồi đáp 1997” và “Lời hồi đáp 1994” đã được lên kế hoạch từ cuối năm 2013 (khi “Lời hồi đáp 1994” vừa đóng máy). Quá trình sản xuất bị đình trệ khá lâu trong năm vừa qua, nhưng giờ đây với bộ phim “Misaeng” như một tấm gương phản chiếu, tvN đang háo hức hơn bao giờ hết khi được mời Đạo diễn Shin Won-ho và biên kịch Lee Woo-jung hợp tác với họ để sản xuất bộ phim vẫn chưa được đặt tên chính thức ấy (mà rất có thể sẽ trở thành một thành công lớn tiếp theo).',
        tag : 'Lee Hye-ri yêu Ryu Jun-yeol'
    },
    {
        id : 13,
        arr: 'seriesMovieBot',
        img: './assets/image/phimLeCapNhat/chuyenTinhBacSi.jpg',
        video : './assets/video/Doctors.mp4',
        name : 'Chuyện tình bác sĩ',
        year : 2017,
        episodes : 30,
        time : '30 tập',
        status : 'Hoàn tất',
        country : 'Phim Hàn Quốc',
        category : 'Phim Tình cảm',
        type : 'Phim truyền hình',       
        directors : ['Oh Choong-Hwan'],
        actors : ['Park Shin-hye', 'Kim Rae-won', 'Lee Sung-kyung', 'Kim Ji-soo'],
        content : 'Cô thiếu nữ ương ngạnh và từng phạm tội gặp 1 giáo viên tận tâm, rồi được truyền cảm hứng để thay đổi và trở thành bác sĩ thần kinh am hiểu cuộc sống đường phố.',
        tag : 'Doctors Love'
    },
]

// export const seriesMovie
export const movieTheaterSmall = [
    {
        id : 2,
        arr: 'movieTheaterSmall',
        img: './assets/image/phimMoiCN/chuyenPhiLy.jpg',
        video : './assets/video/nowWeArebrk.mp4',
        name : 'Chuyện phi lý',
        year : 2021,
        episodes : 0,
        time : '121 phút',
        status : 'HD-VietSub',
        country : 'Phim Trung Quốc',
        category : 'Phim hành động',
        type : 'Phim rạp',       
        directors : ['XUE WEN HUA'],
        actors : ['RYANG ZHANG', 'DONG ZHENG', 'LI XIN ZHE'],
        content : 'Drug Hunting Operation Dưới sự lãnh đạo của đội trưởng Li Guangfeng, Wang Xin, một cảnh sát chống ma túy trẻ tuổi trở về sau khóa huấn luyện đặc biệt tại Nam Mỹ, đã phát động một chiến dịch chống ma túy dưới mật danh "Operation Flash" nhằm phá vỡ âm mưu của trùm ma túy quốc tế Jin Ye và tay buôn ma túy xảo quyệt Xu Dahong. Đối đầu giữa trắng và trắng, đấu tranh giữa thiện và ác, cảnh sát phòng chống ma túy tiền tuyến bắt đầu cuộc chiến chống ma túy bên bờ biển với tinh thần quả cảm, ngoan cường và dám hy sinh!',
        tag : 'Nonsense'
    },
    {
        id : 3,
        arr: 'movieTheaterSmall',
        img: './assets/image/phimMoiCN/truytimkhovang.jpg',
        video : './assets/video/mayHoaAnhTrang.mp4',
        name : 'Truy tìm kho vàng',
        year : 2021,
        episodes : 0,
        time : '90 phút',
        status : 'HD-VietSub',
        country : 'Phim Mỹ',
        category : 'Phim thám hiểm',
        type : 'Phim rạp',       
        directors : ['Edgar Wright'],
        actors : ['Edgar Wright'],
        content : 'Đêm Trước Ở Soho - Last Night in Soho xoay quanh câu chuyện về một người phụ nữ trẻ tuổi có niềm đam mê với ngành nghề thời trang. Thế nhưng, một hôm cô bỗng nhiên quay trở về lại quá khứ vào năm 1960, tại đây cô đã gặp gỡ được vị thần tượng của mình là nữ ca sĩ Wannabe đầy quyết rũ và hào quang. Tuy nhiên, cuộc sống vào năm 1960 không hề như những gì cô nghĩ, nơi đây trang ngập đầy những điều huyền bí và nguy hiểm, và những thứ kinh hoàng mà cô gái sắp phải đối mặt.',
        tag : 'Hunting for gold treasures'
    },
    {
        id : 4,
        arr: 'movieTheaterSmall',
        img: './assets/image/phimMoiCN/demTruocSuHo.jpg',
        video : './assets/video/SOHO.mp4',
        name : 'Đêm trước ở SUHO',
        year : 2021,
        episodes : 0,
        time : '90 phút',
        status : 'HD-VietSub',
        country : 'Phim Mỹ',
        category : 'Phim Hành Động',
        type : 'Phim rạp',       
        directors : ['Edgar Wright'],
        actors : ['Edgar Wright'],
        content : 'Đêm Trước Ở Soho - Last Night in Soho xoay quanh câu chuyện về một người phụ nữ trẻ tuổi có niềm đam mê với ngành nghề thời trang. Thế nhưng, một hôm cô bỗng nhiên quay trở về lại quá khứ vào năm 1960, tại đây cô đã gặp gỡ được vị thần tượng của mình là nữ ca sĩ Wannabe đầy quyết rũ và hào quang. Tuy nhiên, cuộc sống vào năm 1960 không hề như những gì cô nghĩ, nơi đây trang ngập đầy những điều huyền bí và nguy hiểm, và những thứ kinh hoàng mà cô gái sắp phải đối mặt.',
        tag : 'The last night in SOHO'
    },
    {
        id : 5,
        arr: 'movieTheaterSmall',
        img: './assets/image/phimMoiCN/hiemNguy.jfif',
        video : './assets/video/Nevertheless.mp4',
        name : 'Hiểm nguy',
        year : 2021,
        episodes : 0,
        time : '90 phút',
        status : 'HD-VietSub',
        country : 'Phim Mỹ',
        category : 'Phim Hành Động',
        type : 'Phim rạp',       
        directors : ['Edgar Wright'],
        actors : ['Edgar Wright'],
        content : 'Đêm Trước Ở Soho - Last Night in Soho xoay quanh câu chuyện về một người phụ nữ trẻ tuổi có niềm đam mê với ngành nghề thời trang. Thế nhưng, một hôm cô bỗng nhiên quay trở về lại quá khứ vào năm 1960, tại đây cô đã gặp gỡ được vị thần tượng của mình là nữ ca sĩ Wannabe đầy quyết rũ và hào quang. Tuy nhiên, cuộc sống vào năm 1960 không hề như những gì cô nghĩ, nơi đây trang ngập đầy những điều huyền bí và nguy hiểm, và những thứ kinh hoàng mà cô gái sắp phải đối mặt.',
        tag : 'Danger'
    },
    {
        id : 6,
        arr: 'movieTheaterSmall',
        img: './assets/image/phimMoiCN/thamTuTauPho.png',
        video : './assets/video/Nevertheless.mp4',
        name : 'Thám tử tàu phố',
        year : 2021,
        episodes : 0,
        time : '98 phút',
        status : 'HD-VietSub',
        country : 'Phim Trung Quốc',
        category : 'Phim Hành Động',
        type : 'Phim rạp',       
        directors : ['Edgar Wright'],
        actors : ['Edgar Wright'],
        content : 'Hoa tuyết rơi lấy bối cảnh Phong trào đấu tranh dân chủ năm 1987 tại Hàn Quốc nhằm phản đối chính phủ độc tài thời điểm đó và yêu cầu cuộc bầu cử công bằng. Phong trào này kết thúc bằng việc chấm dứt chế độ độc tài của nền cộng hòa thứ 5 ở Hàn Quốc và nền Cộng hòa thứ 6 được thiết lập.  Bộ phim kể về câu chuyện tình đầy lãng mạn nhưng cũng đầy bi thương của hai nhân vật Im Soo-ho (Jung Hae-in) và Eun Young-ro (Kim Ji-Soo). Im Soo-ho là một sinh viên tốt nghiệp, sau khi tham gia một cuộc biểu tình ủng hộ dân chủ, đã được nữ sinh đại học Eun Young-ro vô tình phát hiện trong tình trạng dính đầy máu. Young-ro đã giúp Soo-ho trốn khỏi lực lượng chính phủ và hết lòng chữa trị cho anh bất chấp sự giám sát nghiêm ngặt. Tình yêu của hai người dần nảy nở trong bối cảnh chính trị đầy biến động..',
        tag : 'Street Detective'
    },
    {
        id : 7,
        arr: 'movieTheaterSmall',
        img: './assets/image/phimMoiCN/zara.jfif',
        video : './assets/video/CrashLandingonYou.mp4',
        name : 'ZARA',
        year : 2021,
        episodes : 0,
        time : '98 phút',
        status : 'Hoàn tất',
        country : 'Phim Trung Quốc',
        category : 'Phim Hành Động',
        type : 'Phim rạp',       
        directors : ['Edgar Wright'],
        actors : ['Edgar Wright'],
        content : 'Người tình ánh trăng - Bộ bộ kinh tâm: Lệ là một bộ phim truyền hình Hàn Quốc được chuyển thể từ cuốn tiểu thuyết Bộ Bộ Kinh Tâm của nhà văn Trung Quốc Đồng Hoa.',
        tag : 'ZARA'
    },
]
export const movieTheaterBot = [
    
    {
        id : 8,
        arr: 'movieTheaterBot',
        img: './assets/image/phimMoiCN/ongGiaNoel.png',
        video : './assets/video/moonLover.mp4',
        name : 'Ông già NOEL',
        year : 2021,
        episodes : 0,
        time : '90 phút',
        status : 'HD-Vietsub',
        country : 'Phim Mỹ',
        category : 'Phim hài',
        type : 'Phim rạp',       
        directors : ['Kim Kyu-tae'],
        actors : ['Lee Joon-gi', 'IU', 'Byeon Baek Hyeon', 'Nam Joo-hyuk'],
        content : 'Người tình ánh trăng - Bộ bộ kinh tâm: Lệ là một bộ phim truyền hình Hàn Quốc được chuyển thể từ cuốn tiểu thuyết Bộ Bộ Kinh Tâm của nhà văn Trung Quốc Đồng Hoa.',
        tag : 'Ông già NOEL'
    },
    {
        id : 9,
        arr: 'movieTheaterBot',
        img: './assets/image/phimMoiCN/satThuAnDanh.jpg',
        video : './assets/video/F20.mp4',
        name : 'Sát thủ ẩn danh',
        year : 2021,
        episodes : 0,
        time : '96 phút',
        status : 'sắp chiếu',
        country : 'Phim Mỹ',
        category : 'Phim kinh dị',
        type : 'Phim rạp',       
        directors : ['Hong eun mi'],
        actors : ['jang jong nam', 'Kim Kang Min', 'Yoo Do-hyun'],
        content : ' kể về Ae Ran một người mẹ đơn thân và có một cậu con trai là Do Hoon hiện đang trong thời gian nhập ngũ, cô luôn tự hào về cậu con trai hiền lành và ngoan ngoãn của mình. Thế nhưng, bỗng một hôm cuộc sống của cô suy sụp sau khi phát hiện ra cậu con trai Do Hoon rời khỏi quân ngũ và mắc phải chứng bệnh tâm thần phân liệt. Vì không muốn Do Hoon sống khổ sở nên Ae Ran đã quyết định che giấu đi bệnh của cậu và sống như bình thường. Tuy nhiên, mọi chuyện thay đổi sau khi xuất hiện Kyeong Hwa, người đã biết được các bí mật mà Ae Ran đã che giấu.a.',
        tag : 'Anonymous Assassin'
    },
    {
        id : 10,
        arr: 'movieTheaterBot',
        img: './assets/image/phimMoiCN/satThuXeLan.jpg',
        video : './assets/video/Descendants.mp4',
        name : 'Sát thủ xe lăn',
        year : 2021,
        episodes : 0,
        time : '96 phút',
        status : 'sắp chiếu',
        country : 'Phim Mỹ',
        category : 'Phim kinh dị',
        type : 'Phim rạp',     
        directors : ['Hwang Dong-hyuk'],
        actors : ['Lee Jung-jae', 'Park Hae-soo', 'Wi Ha-joon', 'Jung Ho-yeon'],
        content : 'Hàng trăm người chơi kẹt tiền chấp nhận một lời mời kỳ lạ: thi đấu trong các trò chơi trẻ con. Đón chờ họ là một giải thưởng hấp dẫn – và những rủi ro chết người.',
        tag : 'Wheelchair killer'
    },
    {
        id : 11,
        arr: 'movieTheaterBot',
        img: './assets/image/decu/lenhTruyNaDo.jpg',
        video : './assets/video/THEADDAMS.mp4',
        name : 'Lệnh truy nã đỏ',
        year : 2021,
        episodes : 0,
        time : '90 phút',
        status : 'HD-vietsub',
        country : 'Phim Mỹ',
        category : 'Phim hành động',
        type : 'Phim rạp',       
        directors : ['Charlize Theron'],
        actors : ['Chloë Grace Moretz', 'javon waltong'],
        content : 'Được dịch từ tiếng Anh-Gia đình Addams 2 là bộ phim hài đen siêu nhiên hoạt hình máy tính năm 2021 do Greg Tiernan và Conrad Vernon đạo diễn, Laura Brousseau và Kevin Pavlovic đồng đạo diễn, Dan Hernandez, Benji Samit, Ben Queen và Susanna Fogel viết kịch bản với một câu chuyện của Hernandez và Samit, và dựa trên các nhân vật do Charles ',
        tag : 'Red Wanted Order'
    },
    {
        id : 12,
        arr: 'movieTheaterBot',
        img: './assets/image/phimMoiCN/venum2.jpg',
        video : './assets/video/k2.mp4',
        name : 'Venum 2: Vượt mặt tử thù',
        year : 2021,
        episodes : 0,
        time : '90 phút',
        status : 'HD-Vietsub',
        country : 'Phim Mỹ',
        category : 'Phim hành động',
        type : 'Phim rạp',       
        directors : ['Kim Kyu-tae'],
        actors : ['Lee Joon-gi', 'IU', 'Byeon Baek Hyeon', 'Nam Joo-hyuk'],
        content : 'Người tình ánh trăng - Bộ bộ kinh tâm: Lệ là một bộ phim truyền hình Hàn Quốc được chuyển thể từ cuốn tiểu thuyết Bộ Bộ Kinh Tâm của nhà văn Trung Quốc Đồng Hoa.',
        tag : 'Venum 2'
    },
]
export const newMovieUpdateSmall =  [
    {
        id : 2,
        arr: 'newMovieUpdateSmall',
        img: './assets/image/decu/hanhTinhCat.jpg',
        video : './assets/video/myName.mp4',
        name : 'Dune: Hành tinh cát',
        year : 2021,
        episodes : 0,
        time : '121 phút',
        status : 'HD-VietSub',
        country : 'Phim Mỹ',
        category : 'Phim hành động',
        type : 'Phim rạp',       
        directors : ['XUE WEN HUA'],
        actors : ['RYANG ZHANG', 'DONG ZHENG', 'LI XIN ZHE'],
        content : 'Drug Hunting Operation Dưới sự lãnh đạo của đội trưởng Li Guangfeng, Wang Xin, một cảnh sát chống ma túy trẻ tuổi trở về sau khóa huấn luyện đặc biệt tại Nam Mỹ, đã phát động một chiến dịch chống ma túy dưới mật danh "Operation Flash" nhằm phá vỡ âm mưu của trùm ma túy quốc tế Jin Ye và tay buôn ma túy xảo quyệt Xu Dahong. Đối đầu giữa trắng và trắng, đấu tranh giữa thiện và ác, cảnh sát phòng chống ma túy tiền tuyến bắt đầu cuộc chiến chống ma túy bên bờ biển với tinh thần quả cảm, ngoan cường và dám hy sinh!',
        tag : 'Dune'
    },
    {
        id : 3,
        arr: 'newMovieUpdateSmall',
        img: './assets/image/chieuRap/nguyenRua.jfif',
        video : './assets/video/mayHoaAnhTrang.mp4',
        name : 'Nguyền rủa',
        year : 2021,
        episodes : 0,
        time : '90 phút',
        status : 'HD-VietSub',
        country : 'Phim Mỹ',
        category : 'Phim kinh dị',
        type : 'Phim rạp',       
        directors : ['Edgar Wright'],
        actors : ['Edgar Wright'],
        content : 'Đêm Trước Ở Soho - Last Night in Soho xoay quanh câu chuyện về một người phụ nữ trẻ tuổi có niềm đam mê với ngành nghề thời trang. Thế nhưng, một hôm cô bỗng nhiên quay trở về lại quá khứ vào năm 1960, tại đây cô đã gặp gỡ được vị thần tượng của mình là nữ ca sĩ Wannabe đầy quyết rũ và hào quang. Tuy nhiên, cuộc sống vào năm 1960 không hề như những gì cô nghĩ, nơi đây trang ngập đầy những điều huyền bí và nguy hiểm, và những thứ kinh hoàng mà cô gái sắp phải đối mặt.',
        tag : 'Curse'
    },
    {
        id : 4,
        arr: 'newMovieUpdateSmall',
        img: './assets/image/chieuRap/giaTocGaunt.png',
        video : './assets/video/SOHO.mp4',
        name : 'Gia tộc Gaunt',
        year : 2021,
        episodes : 0,
        time : '90 phút',
        status : 'HD-VietSub',
        country : 'Phim Mỹ',
        category : 'Phim tâm lí',
        type : 'Phim rạp',       
        directors : ['Edgar Wright'],
        actors : ['Edgar Wright'],
        content : 'Hậu Duệ Mặt Trời có nội dung phim xoay quanh hai nhân vật Yoo Shi Jin và Kang Mo Yeon. Yoo Shi Jin là đội trưởng lực lượng gìn giữ hòa bình của Liên Hợp Quốc. Trong khi đó, Kang Mo Yeon là thành viên của tổ chức Bác sĩ không biên giới. Thời gian đầu gặp gỡ và hợp tác, Shi Jin và Mo Yeon thường xuyên xảy ra xung đột. Tuy nhiên về sau, mối quan hệ giữa họ dần được cải thiện. Trải qua nhiều lần xông pha vào chốn hiểm nguy, cả hai đã nhận ra tình cảm dành cho nhau',
        tag : 'Gaunt family'
    },
    {
        id : 5,
        arr: 'newMovieUpdateSmall',
        img: './assets/image/decu/lenhTruyNaDo.jpg',
        video : './assets/video/THEADDAMS.mp4',
        name : 'Gia đình Addams 2',
        year : 2021,
        episodes : 0,
        time : '90 phút',
        status : 'HD-vietsub',
        country : 'Phim Mỹ',
        category : 'Phim hoạt hình',
        type : 'Phim rạp',       
        directors : ['Charlize Theron'],
        actors : ['Chloë Grace Moretz', 'javon waltong'],
        content : 'Được dịch từ tiếng Anh-Gia đình Addams 2 là bộ phim hài đen siêu nhiên hoạt hình máy tính năm 2021 do Greg Tiernan và Conrad Vernon đạo diễn, Laura Brousseau và Kevin Pavlovic đồng đạo diễn, Dan Hernandez, Benji Samit, Ben Queen và Susanna Fogel viết kịch bản với một câu chuyện của Hernandez và Samit, và dựa trên các nhân vật do Charles ',
        tag : 'Addams 2'
    },
    {
        id : 6,
        arr: 'newMovieUpdateSmall',
        img: './assets/image/decu/maBupBeChupky.jpg',
        video : './assets/video/Nevertheless.mp4',
        name : 'Ma búp bê Chupky',
        year : 2021,
        episodes : 0,
        time : '98 phút',
        status : 'HD-VietSub',
        country : 'Phim Mỹ',
        category : 'Phim kinh dị',
        type : 'Phim rạp',       
        directors : ['Edgar Wright'],
        actors : ['Edgar Wright'],
        content : 'Hoa tuyết rơi lấy bối cảnh Phong trào đấu tranh dân chủ năm 1987 tại Hàn Quốc nhằm phản đối chính phủ độc tài thời điểm đó và yêu cầu cuộc bầu cử công bằng. Phong trào này kết thúc bằng việc chấm dứt chế độ độc tài của nền cộng hòa thứ 5 ở Hàn Quốc và nền Cộng hòa thứ 6 được thiết lập.  Bộ phim kể về câu chuyện tình đầy lãng mạn nhưng cũng đầy bi thương của hai nhân vật Im Soo-ho (Jung Hae-in) và Eun Young-ro (Kim Ji-Soo). Im Soo-ho là một sinh viên tốt nghiệp, sau khi tham gia một cuộc biểu tình ủng hộ dân chủ, đã được nữ sinh đại học Eun Young-ro vô tình phát hiện trong tình trạng dính đầy máu. Young-ro đã giúp Soo-ho trốn khỏi lực lượng chính phủ và hết lòng chữa trị cho anh bất chấp sự giám sát nghiêm ngặt. Tình yêu của hai người dần nảy nở trong bối cảnh chính trị đầy biến động..',
        tag : ' Chupky'
    },
    {
        id : 7,
        arr: 'newMovieUpdateSmall',
        img: './assets/image/chieuRap/meToiGanhDoi.jpg',
        video : './assets/video/CrashLandingonYou.mp4',
        name : 'Mẹ tôi gánh đội',
        year : 2021,
        episodes : 0,
        time : '98 phút',
        status : 'Hoàn tất',
        country : 'Phim Thái',
        category : 'Phim hài',
        type : 'Phim rạp',       
        directors : ['Edgar Wright'],
        actors : ['Edgar Wright'],
        content : 'Người tình ánh trăng - Bộ bộ kinh tâm: Lệ là một bộ phim truyền hình Hàn Quốc được chuyển thể từ cuốn tiểu thuyết Bộ Bộ Kinh Tâm của nhà văn Trung Quốc Đồng Hoa.',
        tag : 'My mother carries the team'
    },
   
]
export const newMovieUpdateBot = [
    {
        id : 8,
        arr: 'newMovieUpdateBot',
        img: './assets/image/chieuRap/satNhanBongToi.jfif',
        video : './assets/video/moonLover.mp4',
        name : 'Sát nhân bóng tối',
        year : 2021,
        episodes : 0,
        time : '90 phút',
        status : 'HD-Vietsub',
        country : 'Phim Mỹ',
        category : 'Phim hài',
        type : 'Phim rạp',       
        directors : ['Kim Kyu-tae'],
        actors : ['Lee Joon-gi', 'IU', 'Byeon Baek Hyeon', 'Nam Joo-hyuk'],
        content : 'Phim xoay quanh nhân vật Henry, một người đàn ông dũng cảm và muốn xây dựng một khu đất của riêng mình cùng với con trai. Đây là một bộ phim hành động viễn tây khá xuất sắc, nhận được nhiều lời khen của khán giả và các nhà chuyên môn. Câu chuyện bắt đầu từ hai cha con bắt một người đàn ông bí ẩn bị thương với một túi tiền mặt. Khi một đội quân tự xưng là luật pháp đến đòi tiền, người nông dân phải quyết định tin tưởng ai. Bảo vệ trang trại của mình, Henry bắt buộc phải cầm súng khiến mọi người ngạc nhiên khi gọi danh tính thực sự của anh.',
        tag : 'Shadow Killer'
    },
    {
        id : 9,
        arr: 'newMovieUpdateBot',
        img: './assets/image/decu/xacSong.jfif',
        video : './assets/video/F20.mp4',
        name : 'Xác sống phần 11',
        year : 2021,
        episodes : 0,
        time : '96 phút',
        status : 'HD - Vietsub',
        country : 'Phim Mỹ',
        category : 'Phim kinh dị',
        type : 'Phim rạp',       
        directors : ['Hong eun mi'],
        actors : ['jang jong nam', 'Kim Kang Min', 'Yoo Do-hyun'],
        content : ' kể về Ae Ran một người mẹ đơn thân và có một cậu con trai là Do Hoon hiện đang trong thời gian nhập ngũ, cô luôn tự hào về cậu con trai hiền lành và ngoan ngoãn của mình. Thế nhưng, bỗng một hôm cuộc sống của cô suy sụp sau khi phát hiện ra cậu con trai Do Hoon rời khỏi quân ngũ và mắc phải chứng bệnh tâm thần phân liệt. Vì không muốn Do Hoon sống khổ sở nên Ae Ran đã quyết định che giấu đi bệnh của cậu và sống như bình thường. Tuy nhiên, mọi chuyện thay đổi sau khi xuất hiện Kyeong Hwa, người đã biết được các bí mật mà Ae Ran đã che giấu.a.',
        tag : 'The Walking Dead Part 11'
    },
    {
        id : 10,
        arr: 'newMovieUpdateBot',
        img: './assets/image/phimThinhHanh/shang-chi.jpg',
        video : './assets/video/Descendants.mp4',
        name : 'Shang-Chi và huyền thoại Thập Luân',
        year : 2021,
        episodes : 0,
        time : '96 phút',
        status : 'sắp chiếu',
        country : 'Phim Trung Quốc',
        category : 'Phim hành động',
        type : 'Phim rạp',     
        directors : ['Hwang Dong-hyuk'],
        actors : ['Lee Jung-jae', 'Park Hae-soo', 'Wi Ha-joon', 'Jung Ho-yeon'],
        content : 'Hàng trăm người chơi kẹt tiền chấp nhận một lời mời kỳ lạ: thi đấu trong các trò chơi trẻ con. Đón chờ họ là một giải thưởng hấp dẫn – và những rủi ro chết người.',
        tag : 'Shang-Chi legend'
    },
    {
        id : 11,
        arr: 'newMovieUpdateBot',
        img: './assets/image/decu/lenhTruyNaDo.jpg',
        video : './assets/video/THEADDAMS.mp4',
        name : 'Thám tử lừng danh conan',
        year : 2021,
        episodes : 0,
        time : '90 phút',
        status : 'HD-vietsub',
        country : 'Phim Nhật',
        category : 'Phim hoạt hình',
        type : 'Phim rạp',       
        directors : ['Charlize Theron'],
        actors : ['Chloë Grace Moretz', 'javon waltong'],
        content : 'conan là bộ phim hài đen siêu nhiên hoạt hình máy tính năm 2021 do Greg Tiernan và Conrad Vernon đạo diễn, Laura Brousseau và Kevin Pavlovic đồng đạo diễn, Dan Hernandez, Benji Samit, Ben Queen và Susanna Fogel viết kịch bản với một câu chuyện của Hernandez và Samit, và dựa trên các nhân vật do Charles ',
        tag : 'Conan'
    },
    {
        id : 12,
        arr: 'newMovieUpdateBot',
        img: './assets/image/chieuRap/hienRaNaoMa.jfif',
        video : './assets/video/k2.mp4',
        name : 'Hiện ra nào ma',
        year : 2021,
        episodes : 0,
        time : '90 phút',
        status : 'HD-Vietsub',
        country : 'Phim Mỹ',
        category : 'Phim hành động',
        type : 'Phim rạp',       
        directors : ['Kim Kyu-tae'],
        actors : ['Lee Joon-gi', 'IU', 'Byeon Baek Hyeon', 'Nam Joo-hyuk'],
        content : 'Phim Hiện Ra Nào Ma Kia – Show Me the Ghost (2021) đánh dấu sự trở lại của dòng phim kinh dị hài hước của điện ảnh Hàn Quốc. Nội dung phim Hiện Ra Nào Ma Kia kể về đôi bạn thân Hodu và Yeji, hai bạn trẻ vừa mới ra trường và đang trên con đường theo đuổi, thực hiện ước mơ, hoài bão của mình. ...',
        tag : 'Let show up'
    },
]

export const topFilms = [
    {
        id : 2,
        arr: 'topFilms',
        img: './assets/image/decu/squidGame.jfif',
        video : './assets/video/squidgame.mp4',
        name : 'Trò chơi con mực',
        year : 2021,
        episodes : 9,
        time : '9 tập',
        status : 'Hoàn tất',
        country : 'Phim Hàn Quốc',
        category : 'Kinh dị viễn tưởng',
        type : 'Phim truyền hình',       
        directors : ['Hwang Dong-hyuk'],
        actors : ['Lee Jung-jae', 'Park Hae-soo', 'Wi Ha-joon', 'Jung Ho-yeon'],
        content : 'Hàng trăm người chơi kẹt tiền chấp nhận một lời mời kỳ lạ: thi đấu trong các trò chơi trẻ con. Đón chờ họ là một giải thưởng hấp dẫn – và những rủi ro chết người.',
        tag : 'squid Game'
    },
    {
        id : 3,
        arr: 'topFilms',
        img: './assets/image/decu/NoDie.jfif',
        video : './assets/video/moonLover.mp4',
        name : 'Không phải lúc chết',
        year : 2021,
        episodes : 0,
        time : '90 phút',
        status : 'HD-Vietsub',
        country : 'Phim Mỹ',
        category : 'Phim hành động',
        type : 'Phim rạp',       
        directors : ['Kim Kyu-tae'],
        actors : ['Lee Joon-gi', 'IU', 'Byeon Baek Hyeon', 'Nam Joo-hyuk'],
        content : 'Người tình ánh trăng - Bộ bộ kinh tâm: Lệ là một bộ phim truyền hình Hàn Quốc được chuyển thể từ cuốn tiểu thuyết Bộ Bộ Kinh Tâm của nhà văn Trung Quốc Đồng Hoa.',
        tag : 'no die'
    },
    {
        id : 4,
        arr: 'topFilms',
        img: './assets/image/decu/lenhTruyNaDo.jpg',
        video : './assets/video/GiaNamTruyen.mp4',
        name : 'Lệnh truy nã đỏ',
        year : 2021,
        episodes : 0,
        time : '28 tập',
        status : 'HD-Vietsub',
        country : 'Phim Mỹ',
        category : 'Phim hành động',
        type : 'Phim rạp',       
        directors : ['Lee Gil-bok'],
        actors : ['Cúc Tịnh Y', 'Tăng Tuấn Hy'],
        content : 'Gia Nam Truyện - Mộ Nam Chi Bộ phim Truyền hình [Gia Nam Truyện - Mộ Nam Chi] với những diễn viên nổi tiếng nhất, được bình chọn top phim hay. Bộ phim Truyền hình Gia Nam Truyện (Mộ Nam Chi) kể về câu chuyện tình ngọt ngào nhưng cũng đầy lâm li bi đát của Lý Khiêm và Khương Hiến. Quận chúa Khương Bảo Ninh (Cục Tịnh Y đảm nhận) người bị hạ độc chết ở kiếp trước sau khi được gả cho hoàng đế nhưng bị lạnh nhạt, và bị hãm hại khi lên làm thái hậu nhiếp chính.',
        tag : 'Red Wanted Order'
    },
    {
        id : 5,
        arr: 'topFilms',
        img: './assets/image/phimLeCapNhat/SonghyeO.jpg',
        video : './assets/video/nowWeArebrk.mp4',
        name : 'Bây giờ chúng ta đang chia tay',
        year : 2021,
        episodes : 8,
        time : '8 tập',
        status : 'Đang phát',
        country : 'Phim Hàn Quốc',
        category : 'Phim tình cảm',
        type : 'Phim truyền hình',       
        directors : ['Lee Gil-bok'],
        actors : ['Song Hye-kyo', 'Jang Ki Yong', 'Choi Hee-seo'],
        content : 'Bộ phim là câu chuyện về tình yêu và việc chia tay. Phim lấy bổi cảnh hiện thực trong ngành thời trang. Ha Yeong-eun (Song Hye-kyo) là một trưởng nhóm thiết kế xinh đẹp, sành điệu, thuộc bộ phận thiết kế của công ty thời trang có tên The One. Yoon Jae-gook (Jang Ki-yong) là một nhiếp ảnh gia tự do giàu có.',
        tag : 'Now we are breaking up'
    },
    {
        id : 6,
        arr: 'topFilms',
        img: './assets/image/decu/Adas2.jfif',
        video : './assets/video/THEADDAMS.mp4',
        name : 'Gia đình Addams 2',
        year : 2021,
        episodes : 0,
        time : '90 phút',
        status : 'HD-vietsub',
        country : 'Phim Mỹ',
        category : 'Phim hành động',
        type : 'Phim rạp',       
        directors : ['Charlize Theron'],
        actors : ['Chloë Grace Moretz', 'javon waltong'],
        content : 'Được dịch từ tiếng Anh-Gia đình Addams 2 là bộ phim hài đen siêu nhiên hoạt hình máy tính năm 2021 do Greg Tiernan và Conrad Vernon đạo diễn, Laura Brousseau và Kevin Pavlovic đồng đạo diễn, Dan Hernandez, Benji Samit, Ben Queen và Susanna Fogel viết kịch bản với một câu chuyện của Hernandez và Samit, và dựa trên các nhân vật do Charles ',
        tag : 'Addams 2'
    },
    {
        id : 7,
        arr: 'topFilms',
        img: './assets/image/phimThinhHanh/bânntudianguc.jpeg',
        video : './assets/video/Doctors.mp4',
        name : 'Bản án từ địa ngục',
        year : 2017,
        episodes : 6,
        time : '6 tập',
        status : 'Hoàn tất',
        country : 'Phim Hàn Quốc',
        category : 'Phim hành động',
        type : 'Phim truyền hình',       
        directors : ['Oh Choong-Hwan'],
        actors : ['Park Shin-hye', 'Kim Rae-won', 'Lee Sung-kyung', 'Kim Ji-soo'],
        content : 'Cô thiếu nữ ương ngạnh và từng phạm tội gặp 1 giáo viên tận tâm, rồi được truyền cảm hứng để thay đổi và trở thành bác sĩ thần kinh am hiểu cuộc sống đường phố.',
        tag : 'Doctors Love'
    },
   
    
]
export const comingFilms = [
    {
        id : 1,
        arr: 'comingFilms',
        img: './assets/image/phimLeCapNhat/snopDrop.jpg',
        video : './assets/video/snowDrop.mp4',
        name : 'Snowdrop',
        year : 2021,
        status : 'Sắp chiếu',
        country : 'Phim Hàn Quốc',
        category : 'Phim tình cảm',
        type : 'Phim truyền hình',       
        directors : ['Jo Hyun-tak'],
        actors : ['Kim Ji Soo', 'Jung Hae In'],
        content : 'Hoa tuyết rơi lấy bối cảnh Phong trào đấu tranh dân chủ năm 1987 tại Hàn Quốc nhằm phản đối chính phủ độc tài thời điểm đó và yêu cầu cuộc bầu cử công bằng. Phong trào này kết thúc bằng việc chấm dứt chế độ độc tài của nền cộng hòa thứ 5 ở Hàn Quốc và nền Cộng hòa thứ 6 được thiết lập.  Bộ phim kể về câu chuyện tình đầy lãng mạn nhưng cũng đầy bi thương của hai nhân vật Im Soo-ho (Jung Hae-in) và Eun Young-ro (Kim Ji-Soo). Im Soo-ho là một sinh viên tốt nghiệp, sau khi tham gia một cuộc biểu tình ủng hộ dân chủ, đã được nữ sinh đại học Eun Young-ro vô tình phát hiện trong tình trạng dính đầy máu. Young-ro đã giúp Soo-ho trốn khỏi lực lượng chính phủ và hết lòng chữa trị cho anh bất chấp sự giám sát nghiêm ngặt. Tình yêu của hai người dần nảy nở trong bối cảnh chính trị đầy biến động..',
        tag : 'Ji Soo'
    },
    {
        id : 2,
        arr: 'comingFilms',
        img: './assets/image/sapChieu/avatar2.jpg',
        video : './assets/image/decu/squidGame.jfif',
        name : 'Avatar 2',
        year : 2021,
        status : 'Sắp chiếu',
        country : 'Phim Mỹ',
        category : 'Phim hoạt hình',
        type : 'Phim rạp',       
        directors : ['Hwang Dong-hyuk'],
        actors : ['Lee Jung-jae', 'Park Hae-soo', 'Wi Ha-joon', 'Jung Ho-yeon'],
        content : 'Hàng trăm người chơi kẹt tiền chấp nhận một lời mời kỳ lạ: thi đấu trong các trò chơi trẻ con. Đón chờ họ là một giải thưởng hấp dẫn – và những rủi ro chết người.',
        tag : 'Avatar 2'
    },
    {
        id : 3,
        arr: 'comingFilms',
        img: './assets/image/sapChieu/f20.jpg',
        video : './assets/video/F20.mp4',
        name : 'F20',
        year : 2021,
        status : 'sắp chiếu',
        country : 'Phim Mỹ',
        category : 'Phim hoạt hình',
        type : 'Phim rạp',       
        directors : ['Hong eun mi'],
        actors : ['jang jong nam', 'Kim Kang Min', 'Yoo Do-hyun'],
        content : ' kể về Ae Ran một người mẹ đơn thân và có một cậu con trai là Do Hoon hiện đang trong thời gian nhập ngũ, cô luôn tự hào về cậu con trai hiền lành và ngoan ngoãn của mình. Thế nhưng, bỗng một hôm cuộc sống của cô suy sụp sau khi phát hiện ra cậu con trai Do Hoon rời khỏi quân ngũ và mắc phải chứng bệnh tâm thần phân liệt. Vì không muốn Do Hoon sống khổ sở nên Ae Ran đã quyết định che giấu đi bệnh của cậu và sống như bình thường. Tuy nhiên, mọi chuyện thay đổi sau khi xuất hiện Kyeong Hwa, người đã biết được các bí mật mà Ae Ran đã che giấu.a.',
        tag : 'F20'
    },
    {
        id : 4,
        arr: 'comingFilms',
        img: './assets/image/sapChieu/gac.jpg',
        video : './assets/video/Nevertheless.mp4',
        name : 'Dẫu biết',
        year : 2021,
        status : 'Sắp chiếu',
        country : 'Phim Hàn Quốc',
        category : 'Phim kinh dị',
        type : 'Phim truyền hình',       
        directors : ['Ga-Ram Kim'],
        actors : ['Song Kang', 'Han So hee', 'Chae Jong-hyeop'],
        content : 'Diễn viên: Han So Hee , Song Kang, Chae Jong Hyeop, Lee Yeol Eum, Yang Hye Ji, Kim Min Gwi Dẫu Biết (Nevertheless 2021) là bộ phim của Netflix thuộc thể loại drama chính kịch. Phim xoay quanh câu chuyện của cô nàng trước sức mê hoặc của anh bạn cùng trường nghệ thuật giỏi tán tỉnh, cô nàng hoài nghi tình yêu, dù do dự vẫn bị kéo vào mối quan hệ thể xác nhưng chỉ là bạn bè.',
        tag : 'Never the less'
    },
    {
        id : 5,
        arr: 'comingFilms',
        img: './assets/image/sapChieu/bigMouse.jpg',
        video : './assets/video/YouthofMay.mp4',
        name : 'Big Mouth',
        year : 2021,
        status : 'Sắp chiếu',
        country : 'Phim Hàn Quốc',
        category : 'Phim tình cảm',
        type : 'Phim truyền hình',       
        directors : ['Song Min-yeob'],
        actors : ['YoonA (SNSD)', 'Lee Jong Suk '],
        content : 'Lee Jong Suk đảm nhận vai Park Chang Ho, một luật sư tầm thường. Anh được mọi người trong giới luật gọi là "Big Mouth" vì tính cách khoa trương. Yoona vào vai y tá Go Mi Ho, vợ của Park Chang Ho, người đã đưa Park trở thành luật sư. Thời đại học, Go được biết đến với vẻ đẹp nổi bật, thanh lịch và tự tin. Nhưng sau khi kết hôn với một người đàn ông thiếu tham vọng, cô dần trở nên ích kỷ, hay chửi thề, chua ngoa với mục đích biến đức ông chồng trở nên xứng đáng với mình. Tuy vậy, Go cũng tìm mọi cách giúp chồng rửa sạch hiềm nghi khi Park bị nhầm thành kẻ lừa đảo.',
        tag : 'Big Mouth'
    },
    {
        id : 6,
        arr: 'comingFilms',
        img: './assets/image/sapChieu/khachsanhuyenbi4.jpg',
        video : './assets/video/TheLegend.mp4',
        name : 'Khách sạn huyền bí 4: Ma Cà Rồng biến hình',
        year : 2021,
        status : 'Sắp chiếu',
        country : 'Phim Hàn Quốc',
        category : 'Phim kinh dị',
        type : 'Phim rạp',       
        directors : ['Jin Hyuk'],
        actors : ['Lee Min-ho', 'Jun Ji-hyun', 'Shin Won-ho', 'Lee Hee-joon'],
        content : 'Khách sạn huyền bí: Ma cà rồng biến hình là một bộ phim hài hoạt hình sắp ra mắt của Mỹ do Sony Pictures Animation sản xuất và Sony Pictures Releasing phân phối.',
        tag : 'Hotel Transylvania: Transformania'
    },
    {
        id : 7,
        arr: 'comingFilms', 
       img: './assets/image/sapChieu/nguoiDoi.jpg',
        video : './assets/video/Reply1988.mp4',
        name : 'Người dơi',
        year : '2021',
        status : 'Sắp chiếu',
        country : 'Phim Mỹ',
        category : 'Phim Tâm Lý Hài Hước',
        type : 'Phim rạp',       
        directors : ['Shin Won-ho'],
        actors : ['Lee Hye-ri', 'Ryu Jun-yeol', 'Park Bo-gum', 'Go Kyung-pyo'],
        content : 'Bộ phim thứ ba của những nhà sản xuất đã từng rất thành công với hai phim trước đó là “Lời hồi đáp 1997” và “Lời hồi đáp 1994” đã được lên kế hoạch từ cuối năm 2013 (khi “Lời hồi đáp 1994” vừa đóng máy). Quá trình sản xuất bị đình trệ khá lâu trong năm vừa qua, nhưng giờ đây với bộ phim “Misaeng” như một tấm gương phản chiếu, tvN đang háo hức hơn bao giờ hết khi được mời Đạo diễn Shin Won-ho và biên kịch Lee Woo-jung hợp tác với họ để sản xuất bộ phim vẫn chưa được đặt tên chính thức ấy (mà rất có thể sẽ trở thành một thành công lớn tiếp theo).',
        tag : 'Bad man'
    },
    {
        id : 8,
        arr: 'comingFilms',  
        img: './assets/image/sapChieu/nguoiNhenKhongConNha.jpg',
        video : './assets/video/Doctors.mp4',
        name : 'Người nhện: không còn nhà',
        year : 2021,
        status : 'Sắp chiếu',
        country : 'Phim Anh',
        category : 'Phim viễn tưởng',
        type : 'Phim rạp',       
        directors : ['Oh Choong-Hwan'],
        actors : ['Park Shin-hye', 'Kim Rae-won', 'Lee Sung-kyung', 'Kim Ji-soo'],
        content : 'Người Nhện không còn nhà là phim siêu anh hùng năm 2021 của Mỹ dựa trên nhân vật Peter Parker của Marvel Comics, do Columbia Pictures và Marvel Studios đồng sản xuất, và được phân phối bởi Sony Pictures Releasing. ',
        tag : 'Spider men'
    },
    {
        id : 9,
        arr: 'comingFilms',  
        img: './assets/image/sapChieu/oRe.jpg',
        video : './assets/video/moonLover.mp4',
        name : 'Ở rể: Cát Hưng Cao Chiếu',
        year : 2021,
        status : 'Sắp chiếu',
        country : 'Phim Hàn Quốc',
        category : 'Phim Tình cảm',
        type : 'Phim truyền hình',       
        directors : ['Kim Kyu-tae'],
        actors : ['Lee Joon-gi', 'IU', 'Byeon Baek Hyeon', 'Nam Joo-hyuk'],
        content : 'Ở Rể: Cát Hưng Cao Chiếu là phần phim xoay quanh thiếu gia nhị phòng của gia đình buôn vải họ Tô. Từng muốn tranh giành vị trí kế thừa gia tộc họ Tô, nhưng anh chàng lại bị Ninh Nghị đánh bại trong cuộc đua cạnh tranh với em gái Tô Đàn Nhi.',
        tag : 'Moon Love'
    },
    {
        id : 10,
         arr: 'comingFilms',
        img: './assets/image/sapChieu/thanhphoRaccon.jpg',
        video : './assets/video/SOHO.mp4',
        name : 'Resident Evil: Thành Phố Raccoon',
        year : 2021,
        episodes : 0,
        time : '95 phút',
        status : 'HD-VietSub',
        country : 'Phim Trung Quốc',
        category : 'Phim hành động',
        type : 'Phim rạp',       
        directors : ['XUE WEN HUA'],
        actors : ['RYANG ZHANG', 'DONG ZHENG', 'LI XIN ZHE'],
        content : 'Drug Hunting Operation Dưới sự lãnh đạo của đội trưởng Li Guangfeng, Wang Xin, một cảnh sát chống ma túy trẻ tuổi trở về sau khóa huấn luyện đặc biệt tại Nam Mỹ, đã phát động một chiến dịch chống ma túy dưới mật danh "Operation Flash" nhằm phá vỡ âm mưu của trùm ma túy quốc tế Jin Ye và tay buôn ma túy xảo quyệt Xu Dahong. Đối đầu giữa trắng và trắng, đấu tranh giữa thiện và ác, cảnh sát phòng chống ma túy tiền tuyến bắt đầu cuộc chiến chống ma túy bên bờ biển với tinh thần quả cảm, ngoan cường và dám hy sinh!',
        tag : 'drug hunting operation'
    },
]
export const specialFirst = [
    {
        id : 1,
        arr: 'specialFirst',
        img: './assets/image/phimLeCapNhat/snopDrop.jpg',
        video : './assets/video/snowDrop.mp4',
        name : 'Snowdrop',
        year : 2021,
        status : 'Sắp chiếu',
        country : 'Phim Hàn Quốc',
        category : 'Phim tình cảm',
        type : 'Phim truyền hình',       
        directors : ['Jo Hyun-tak'],
        actors : ['Kim Ji Soo', 'Jung Hae In'],
        content : 'Hoa tuyết rơi lấy bối cảnh Phong trào đấu tranh dân chủ năm 1987 tại Hàn Quốc nhằm phản đối chính phủ độc tài thời điểm đó và yêu cầu cuộc bầu cử công bằng. Phong trào này kết thúc bằng việc chấm dứt chế độ độc tài của nền cộng hòa thứ 5 ở Hàn Quốc và nền Cộng hòa thứ 6 được thiết lập.  Bộ phim kể về câu chuyện tình đầy lãng mạn nhưng cũng đầy bi thương của hai nhân vật Im Soo-ho (Jung Hae-in) và Eun Young-ro (Kim Ji-Soo). Im Soo-ho là một sinh viên tốt nghiệp, sau khi tham gia một cuộc biểu tình ủng hộ dân chủ, đã được nữ sinh đại học Eun Young-ro vô tình phát hiện trong tình trạng dính đầy máu. Young-ro đã giúp Soo-ho trốn khỏi lực lượng chính phủ và hết lòng chữa trị cho anh bất chấp sự giám sát nghiêm ngặt. Tình yêu của hai người dần nảy nở trong bối cảnh chính trị đầy biến động..',
        tag : 'Ji Soo'
    },
    {
        id : 2,
        arr: 'specialFirst',
        img: './assets/image/phimMoiCN/bietDoiTruyQuetMT.jfif',
        video : './assets/video/tryQuetMatuy.mp4',
        name : 'Biệt đội truy quét ma túy',
        year : 2021,
        episodes : 0,
        time : '95 phút',
        status : 'HD-VietSub',
        country : 'Phim Trung Quốc',
        category : 'Phim hành động',
        type : 'Phim rạp',       
        directors : ['XUE WEN HUA'],
        actors : ['RYANG ZHANG', 'DONG ZHENG', 'LI XIN ZHE'],
        content : 'Drug Hunting Operation Dưới sự lãnh đạo của đội trưởng Li Guangfeng, Wang Xin, một cảnh sát chống ma túy trẻ tuổi trở về sau khóa huấn luyện đặc biệt tại Nam Mỹ, đã phát động một chiến dịch chống ma túy dưới mật danh "Operation Flash" nhằm phá vỡ âm mưu của trùm ma túy quốc tế Jin Ye và tay buôn ma túy xảo quyệt Xu Dahong. Đối đầu giữa trắng và trắng, đấu tranh giữa thiện và ác, cảnh sát phòng chống ma túy tiền tuyến bắt đầu cuộc chiến chống ma túy bên bờ biển với tinh thần quả cảm, ngoan cường và dám hy sinh!',
        tag : 'drug hunting operation'
    },
    {
        id : 3,
        arr: 'specialFirst',
        img: './assets/image/phimMoiCN/bietDoiTruyQuetMT.jfif',
        video : './assets/video/tryQuetMatuy.mp4',
        name : 'Dạ quỷ rừng sâu',
        year : 2021,
        episodes : 0,
        time : '95 phút',
        status : 'HD-VietSub',
        country : 'Phim Mỹ',
        category : 'Phim hành động, kinh dị',
        type : 'Phim rạp',       
        directors : ['XUE WEN HUA'],
        actors : ['RYANG ZHANG', 'DONG ZHENG', 'LI XIN ZHE'],
        content : 'Là tác phẩm được thực hiện từ những câu chuyện có thật về Góa Phụ - linh hồn quỷ dữ chuyên bắt cóc những người vô tội vô tình bị lạc vào rừng. Không ai biết Góa Phụ làm gì những nạn nhân mà nó bắt được, chỉ biết rằng họ luôn được tìm thấy khi đã chết, trên người hoàn toàn không có mảnh vải che thân, cũng không tìm thấy dấu hiệu nào bị tra tấn, bạo lực. Ám ảnh về Góa Phụ khiến tất cả những người dân quanh vùng Leningrad đều không dám bén mảng vào rừng, ngoại trừ những người làm nhiệm vụ cứu hộ.',
        tag : 'drug hunting operation'
    },
    {
        id : 4,
        arr: 'specialFirst',
        video : './assets/video/Arcane.mp4',
        img: './assets/image/decu/arcane.jfif',
        name : 'Liên minh huyền thoại',
        year : 2021,
        episodes : 0,
        time : '90 phút',
        status : 'Hoàn tất',
        country : 'Phim Mỹ',
        category : 'Phim hành động',
        type : 'Phim rạp',       
        directors : ['Potsy Ponciroli'],
        actors : ['Tim Blake Nelson', 'Scott Haze'],
        content : 'Phim xoay quanh nhân vật Henry, một người đàn ông dũng cảm và muốn xây dựng một khu đất của riêng mình cùng với con trai. Đây là một bộ phim hành động viễn tây khá xuất sắc, nhận được nhiều lời khen của khán giả và các nhà chuyên môn. Câu chuyện bắt đầu từ hai cha con bắt một người đàn ông bí ẩn bị thương với một túi tiền mặt. Khi một đội quân tự xưng là luật pháp đến đòi tiền, người nông dân phải quyết định tin tưởng ai. Bảo vệ trang trại của mình, Henry bắt buộc phải cầm súng khiến mọi người ngạc nhiên khi gọi danh tính thực sự của anh.',
        tag : 'old henry'
    },
]
